import turtle

p = turtle.Pen()

colors = ["red"]

p.speed(-3)

for x in range(1):
        p.right(90)
        p.forward(200)
        p.right(90)
        p.forward(150)
        p.right(90)
        p.forward(200)
        p.back(30)
        p.right(90)
        p.forward(150)
        p.right(90)
        p.forward(30)
        p.right(90)
        p.forward(150)
        p.right(90)
        p.back(30)
        p.right(90)
        p.forward(150)
        p.right(90)
        p.forward (80)
        p.right(90)
        p.forward(150)
        p.right(90)
        p.forward(20)
        p.right(90)
        p.forward(150)
        p.left(90)
        p.forward(20)
        p.left(90)
        p.forward(150)
        p.right(90)
        p.forward(20)
        p.right(90)
        p.forward(150)
        p.right(90)
        p.back(110)
        p.right(90)
        p.forward(150)
        p.left(90)
        p.forward(60)
        p.left(90)
        p.forward(20)
        p.right(90)
        p.forward(140)
        p.left(90)
        p.forward(20)
        p.left(90)
        p.forward(140)
        p.right(90)
        p.forward(20)
        p.right(90)
        p.forward(140)
        p.right(90)
        p.forward(20)
        p.right(90)
        
        
        
turtle.done()